### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by Stefanuk12** [Belkworks/tape#11]
This doesn't really make a difference but would be nice to see. Essentially match the indentations but if the original file is not indented, ignore that (see second example)

# Examples

## First
```lua
-- module: init.lua
__tape.chunks["init.lua"] = function(script)
-- // METADATA
ScriptVersion = "1.9.0"
``` 
->
 ```lua
-- module: init.lua
__tape.chunks["init.lua"] = function(script)
    -- // METADATA
    ScriptVersion = "1.9.0"
```

## Second

```lua
local function bad_indent()
return true
end
```
->
 ```lua
-- module: init.lua
__tape.chunks["init.lua"] = function(script)
    local function bad_indent()
    return true
    end
end
```

**Comment by safazi** [comment]
Closed by https://github.com/Belkworks/tape/commit/f2215eca900bfebb8bcd0555656fe197f44fcecb
