### ISSUE TITLE
Add support for Roblox LSP

### ISSUE THREAD

**Issue by Stefanuk12** [Belkworks/tape#13]
Currently, Roblox LSP gives the "any" type when you use require. It would be awesome to create a plug-in for it in order to support intellisense for tape's version of require.

**Comment by safazi** [comment]
Please use `require(script.Parent.whatever)` style for LSP to work

**Comment by Stefanuk12** [comment]
I am using that format, unfortunately, Roblox LSP (the VS Code extension) does not recognise it. If I'm doing something wrong, please let me know and make a guide. Thanks.
